#!/bin/bash

set -e

make test

perl -e '`git status` =~ /working directory clean/ or die "cannot publish without clean working dir - git status:\n" . `git status`'

echo current version is `perl -ne 'print /"version"\s*:\s*"(\d+\.\d+\.\d+)"/' package.json`

perl -e 'print "new version? "'

read new_version

perl -i -pe 's/("version"\s*:\s*\")(?:|\d+\.\d+\.\d+)(")/$$1."'$$new_version'".$$2/e' package.json

git commit -m 'Version for release' package.json

git tag v$$new_version

git push origin master

git push --tags

