#!/bin/bash

set -e

version=`perl -ne 'print /"version"\s*:\s*"(\d+\.\d+\.\d+)"/' package.json`

echo publishing $version

make dist VERSION=$version

npm publish on-v$version.tar.gz

github_upload target/amd/on.js tomyan/on.js
github_upload target/amd/on.debug.js tomyan/on.js
github_upload target/amd/on.named.js tomyan/on.js
github_upload target/amd/on.named.debug.js tomyan/on.js

github_upload target/global/on.global.js
github_upload target/global/on.global.debug.js

